#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Raw bytes of stream_state_internal_quant.tflite embedded at build time.
 * The .c file is generated by:
 *   xxd -i stream_state_internal_quant.tflite > wake_model_data.c
 * (run from the repo root, or adjust paths accordingly)                   */
extern const unsigned char stream_state_internal_quant_tflite[];
extern const unsigned int  stream_state_internal_quant_tflite_len;

#ifdef __cplusplus
}
#endif
